export enum UserRolesType {
  Member,
  Admin,
}

export enum ProcessSignals {
  SIGTERM = 'SIGTERM'
}

export enum SystemErrors {
  EADDRINUSE = 'EADDRINUSE'
}

export enum Errors {
/* User Errors */
ERROR_COULD_NOT_DELETE_USER_BY_ID = "ERROR_COULD_NOT_DELETE_USER_BY_ID",
ERROR_PASSWORD_CRITERIA_NOT_MET = "ERROR_PASSWORD_CRITERIA_NOT_MET",
ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD",
ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL",
ERROR_INVALID_NAME = "ERROR_INVALID_NAME",
ERROR_USER_EXISTS = "ERROR_USER_EXISTS",
  /* -- */ 
  ERROR_MISSING_PARAMETER = "ERROR_MISSING_PARAMETER",
  ERROR_LOGIN_FAILED = "ERROR_LOGIN_FAILED",
}

export enum StatusCodes {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  NOT_MODIFIED = 304,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  UNSUPPORTED_MEDIA_TYPE = 415,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  GATEWAY_TIMEOUT = 504,
}
